# Generated by Django 5.2 on 2025-04-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
