# Generated by Django 5.2 on 2025-05-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0010_inventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='hsn_sac_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
