# Generated by Django 5.2 on 2025-06-21 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0012_payment_collected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('checklist_not_washed', models.BooleanField(default=False)),
                ('checklist_not_cut', models.BooleanField(default=False)),
                ('checklist_ppe_intact', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailapp.customer')),
                ('purchased_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailapp.purchaseitem')),
                ('replacement_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retailapp.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('photo', models.ImageField(upload_to='return_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailapp.customer')),
                ('purchased_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailapp.purchaseitem')),
            ],
        ),
    ]
