# Generated by Django 5.2 on 2025-06-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0013_payment_reference_id_exchangerequest_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dresspurchase',
            name='auto_purchase_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='auto_payment_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dresspurchase',
            name='purchase_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
