# Generated by Django 5.2 on 2025-06-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0014_dresspurchase_auto_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
