# Generated by Django 5.2 on 2025-07-06 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0015_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='retailapp.customer'),
        ),
        migrations.AlterField(
            model_name='dresspurchase',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dress_purchase', to='retailapp.customer'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_request', to='retailapp.customer'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='purchased_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_request', to='retailapp.purchaseitem'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='retailapp.dresspurchase'),
        ),
        migrations.AlterField(
            model_name='returnorexchange',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_exchange', to='retailapp.dresspurchase'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='retailapp.customer'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='purchased_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='retailapp.purchaseitem'),
        ),
    ]
