# Generated by Django 5.2 on 2025-07-06 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0016_payment_customer_alter_dresspurchase_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='retailapp.customer'),
        ),
    ]
