# Generated by Django 5.2 on 2025-07-06 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0018_alter_payment_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='purchase',
        ),
    ]
