# Generated by Django 5.2 on 2025-04-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0004_remove_dresspurchase_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
