# Generated by Django 5.2 on 2025-04-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0005_remove_customer_user_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
