# Generated by Django 5.2 on 2025-04-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0006_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dresspurchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
