# Generated by Django 5.2 on 2025-05-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0008_alter_dresspurchase_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
