# Generated by Django 5.2 on 2025-05-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0011_alter_inventoryitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='collected_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
